name: application 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "13 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # install the python version needed

      - name: cache python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          LOCATION: ${{ secrets.LOCATION1 }}
          NUMBER: ${{ secrets.NUMBER1 }}
          PASSPORT_NUMBER: ${{ secrets.PASSPORT_NUMBER1 }}
          SURNAME: ${{ secrets.SURNAME1 }}
          TIMEZONE: ${{ secrets.TIMEZONE }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP: ${{ secrets.SMTP }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python trigger.py
